version: '3.8'

services:
  mun-frontend-app:
    image: blogapp-front-image3-p
    build:
      context: ./frontend/
      dockerfile: Dockerfile 
    ports:
      - 3000:80
    container_name: mun-dev-frontend-kontti3-p

  mun-backend-app:
    image: blogapp-back-image3-p
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 3003:3003
    container_name: blogapp-back-kontti3-p

  nginx:
    image: nginx:1.24
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80 # this is needed
    container_name: reverse-proxy
    depends_on:
      - mun-frontend-app
    #  - mun-backend-app

########## building and testing commands ###############
## docker compose up
## docker compose down

## tests: 
#    docker ps
#    browser: http://localhost:8080

